name: Create release tag
on:
    push:
        tags:
            - '*'
jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create release tag
              id: create_release
              uses: elgohr/Github-Release-Action@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  title: Release ${{ github.ref }}
                  draft: false
                  prerelease: false